apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  namespace: spring
  labels:
    app: combined-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot-container
          image: team57-server-container-image.kr.ncr.ntruss.com/willbe-server:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred

