apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  namespace: spring-log
  labels:
    app: willbe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: willbe-app
  template:
    metadata:
      labels:
        app: willbe-app
    spec:
      containers:
        - name: springboot-container
          image: team57-container-image.kr.ncr.ntruss.com/willbe-logging:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred

