apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: dju-trainee1
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
    - name: mysql-port
      port: 3306
      targetPort: 3306
      nodePort: 31128

