apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  namespace: spring
  labels:
    app: willbe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: willbe-app
  template:
    metadata:
      labels:
        app: willbe-app
    spec:
      containers:
        - name: springboot-container
          image: team57-server-container-image.kr.ncr.ntruss.com/willbe-server:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"

      imagePullSecrets:
        - name: regcred

