apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: spring
spec:
  type: LoadBalancer
  selector:
    app: willbe-app
  ports:
    - port: 80          # 외부에서 접속할 포트 (HTTP 기본 포트)
      targetPort: 8080         # Spring Boot 컨테이너에서 사용하는 포트
      protocol: TCP

