# all-in-one.yaml

---
apiVersion: v1
kind: Namespace
metadata:
  name: springboot-namespace
  labels:
    name: springboot-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  namespace: springboot-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-container
          image: team57-server-container-image.kr.ncr.ntruss.com/willbe-server:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_HOST
              value: "mysql-service.mysql-namespace.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "WillBeDB"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: "rootpassword"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
      imagePullSecrets:
        - name: ncp-registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: springboot-namespace
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

